queue:
  name: Default
  demands: 
  - msbuild
  - visualstudio

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1


- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

- task: PowerShell@1
  displayName: 'Checkout TSHelper branch'
  inputs:
    scriptName: PreapreTSHelper.ps1

    arguments: '-BranchName v-wedin/AddAzureScript'

- task: BatchScript@1
  displayName: 'Build RDPServer'
  inputs:
    filename: TestSuites/RDP/Server/src/build.cmd

- task: PowerShell@1
  displayName: 'Setup TestSuite Environment'
  inputs:
    scriptName: AzureScripts/Setup-TestSuiteEnvironment.ps1


